// import React from "react";
import {Link} from "react-router-dom";

const OffsetProgram = () => {
  return (
    <div className="bg-gray-100 min-h-screen py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto text-center">
          <h1 className="text-4xl font-extrabold text-gray-900 sm:text-5xl">
            Carbon Offset Program
          </h1>
          <p className="mt-4 text-xl text-gray-600">
            At Eco Delivery, we understand the importance of minimizing our
            environmental impact. That’s why we’ve implemented a comprehensive
            carbon offset program to neutralize the emissions generated by our
            operations.
          </p>
        </div>

        <div className="mt-12 grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* How It Works Section */}
          <div className="bg-white shadow-md rounded-lg p-6">
            <h2 className="text-2xl font-semibold text-gray-800">
              How It Works
            </h2>
            <p className="mt-4 text-gray-700">
              Our carbon offset program is designed to reduce and offset the
              emissions produced by our delivery fleet. For every kilometer
              traveled by our vehicles, we invest in environmental projects that
              absorb or prevent carbon emissions.
            </p>
            <ul className="mt-4 list-disc list-inside text-left text-gray-700">
              <li>Renewable energy investments</li>
              <li>Reforestation projects</li>
              <li>Carbon capture technology</li>
            </ul>
          </div>

          {/* Impact Metrics Section */}
          <div className="bg-white shadow-md rounded-lg p-6">
            <h2 className="text-2xl font-semibold text-gray-800">Our Impact</h2>
            <p className="mt-4 text-gray-700">
              Since launching the program, we have successfully offset over 500
              metric tons of CO₂. We are on track to offset 100% of our carbon
              emissions by 2025.
            </p>
            <div className="mt-6 flex justify-center">
              <div className="text-center">
                <span className="text-4xl font-bold text-green-800">500+</span>
                <p className="text-gray-700">Metric Tons CO₂ Offset</p>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Project 1 */}
          <div className="bg-white shadow-md rounded-lg p-6">
            <h3 className="text-xl font-semibold text-gray-800">
              Reforestation
            </h3>
            <p className="mt-4 text-gray-700">
              We support reforestation projects in key regions around the globe,
              planting thousands of trees to absorb CO₂ from the atmosphere.
            </p>
          </div>

          {/* Project 2 */}
          <div className="bg-white shadow-md rounded-lg p-6">
            <h3 className="text-xl font-semibold text-gray-800">
              Renewable Energy
            </h3>
            <p className="mt-4 text-gray-700">
              Our investments in renewable energy projects help reduce
              dependency on fossil fuels, preventing new emissions from being
              released.
            </p>
          </div>

          {/* Project 3 */}
          <div className="bg-white shadow-md rounded-lg p-6">
            <h3 className="text-xl font-semibold text-gray-800">
              Carbon Capture
            </h3>
            <p className="mt-4 text-gray-700">
              We&#39;re advancing carbon capture technologies, which are essential
              for capturing and storing carbon emissions before they reach the
              atmosphere.
            </p>
          </div>
        </div>

        <div className="mt-16 text-center">
          <h2 className="text-3xl font-bold text-green-800">
            Partner with Us for a Greener Future
          </h2>
          <p className="mt-4 text-lg text-gray-700">
            Together, we can make a significant impact on climate change. Learn
            more about how you can support our carbon offset initiatives.
          </p>
          <Link
            to="/sustainability/tips"
            className="mt-8 inline-block bg-green-600 hover:bg-green-700 text-white text-lg font-semibold py-3 px-8 rounded-full"
          >
            Learn More
          </Link>
        </div>
      </div>
    </div>
  );
};

export default OffsetProgram;
